name: Replicate Files
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 3'

jobs:
    replicate-file:
    runs-on: ubuntu-latest
        name: Replicate Files

        steps:
        - name: Checkout EasyDutch
          uses: actions/checkout@v2
          with:
            path: ./EasyDutch

        - name: Checkout AdBlockFilters
          uses: actions/checkout@master
          with: 
            repository: BPower0036/AdBlockFilters
            token: ${{ secrets.ACTIONS_TOKEN }}
            path: BPower0036/AdBlockFilters/EasyDutch

        - name: Copy/Create Anti-Adblock.txt
          run: |
            FILE=./EasyDutch/EasyDutch/Anti-Adblock.txt
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./EasyDutch/EasyDutch/Anti-Adblock.txt BPower0036/AdBlockFilters
            else 
              echo "Creating $FILE"
              touch BPower0036/AdBlockFilters/EasyDutch/Anti-Adblock.txt
            fi
        - name: Copy/Create Block_General.txt
          run: |
            FILE=./EasyDutch/EasyDutch/Block_General.txt
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./EasyDutch/EasyDutch/Block_General.txt BPower0036/AdBlockFilters
            else 
              echo "Creating $FILE"
              touch BPower0036/AdBlockFilters/EasyDutch/Block_General.txt
            fi
        - name: Copy/Create Block_Resources.txt
          run: |
            FILE=./EasyDutch/EasyDutch/Block_Resources.txt
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./EasyDutch/EasyDutch/Block_Resources.txt BPower0036/AdBlockFilters
            else 
              echo "Creating $FILE"
              touch BPower0036/AdBlockFilters/EasyDutch/Block_Resources.txt
            fi
        - name: Copy/Create file
          run: |
            FILE=./EasyDutch/EasyDutch/Block_Whitelist.txt
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./EasyDutch/EasyDutch/Block_Whitelist.txt BPower0036/AdBlockFilters
            else 
              echo "Creating $FILE"
              touch BPower0036/AdBlockFilters/EasyDutch/Block_Whitelist.txt
            fi
        - name: Copy/Create Block_first_party_Server.txt
          run: |
            FILE=./EasyDutch/EasyDutch/Block_first_party_Server.txt
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./EasyDutch/EasyDutch/Block_first_party_Server.txt BPower0036/AdBlockFilters
            else 
              echo "Creating $FILE"
              touch BPower0036/AdBlockFilters/EasyDutch/Block_first_party_Server.txt
            fi
        - name: Copy/Create Block_third_party_Server.txt
          run: |
            FILE=./EasyDutch/EasyDutch/Block_third_party_Server.txt
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./EasyDutch/EasyDutch/Block_third_party_Server.txt BPower0036/AdBlockFilters
            else 
              echo "Creating $FILE"
              touch BPower0036/AdBlockFilters/EasyDutch/Block_third_party_Server.txt
            fi
        - name: Copy/Create Hide_General.txt
          run: |
            FILE=./EasyDutch/EasyDutch/Hide_General.txt
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./EasyDutch/EasyDutch/Hide_General.txt BPower0036/AdBlockFilters
            else 
              echo "Creating $FILE"
              touch BPower0036/AdBlockFilters/EasyDutch/Hide_General.txt
            fi
        - name: Copy/Create Hide_Specific.txt
          run: |
            FILE=./EasyDutch/EasyDutch/Hide_Specific.txt
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./EasyDutch/EasyDutch/Hide_Specific.txt BPower0036/AdBlockFilters
            else 
              echo "Creating $FILE"
              touch BPower0036/AdBlockFilters/EasyDutch/Hide_Specific.txt
            fi
        - name: Copy/Create Hide_Whitelist.txt
          run: |
            FILE=./EasyDutch/EasyDutch/Hide_Whitelist.txt
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./EasyDutch/EasyDutch/Hide_Whitelist.txt BPower0036/AdBlockFilters
            else 
              echo "Creating $FILE"
              touch BPower0036/AdBlockFilters/EasyDutch/Hide_Whitelist.txt
            fi
        - name: Copy/Create No_uBlock_Filters.txt
          run: |
            FILE=./EasyDutch/EasyDutch/No_uBlock_Filters.txt
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./EasyDutch/EasyDutch/No_uBlock_Filters.txt BPower0036/AdBlockFilters
            else 
              echo "Creating $FILE"
              touch BPower0036/AdBlockFilters/EasyDutch/No_uBlock_Filters.txt
            fi

        - name: Push AdBlockFilters
          run: |
            cd BPower0036/AdBlockFilters
            git add .
            git config user.name "GitHub-Actions bot"
            git config user.email "<>"
            git commit -am "File Replicated from EasyDutch"
            git push
