name: Deploy to gh-pages branch

on:
  push:
    branches:
      - main
    paths:
      - 'EasyDutch/**'
      - 'EasyDutch.txt'

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write  # for Git to git push
    name: Publish lists
    runs-on: ubuntu-latest
    steps:
      - name: Clone EasyDutch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      # - name: Change permissions
      #  run: git update-index --chmod=+x ./tools/make-easydutch.sh
      - name: Copy filter lists to gh-pages
        run: |
          TMPDIR=$(mktemp -d)
          git clone --depth=1 https://github.com/EasyDutch-uBO/EasyDutch.git $TMPDIR
          pushd $TMPDIR > /dev/null
          # ./tools/make-easydutch.sh
          echo "*** EasyDutch: Assembling EasyDutch.txt"
          node ./tools/make-list.js in=./tools/easydutch-filters.template out=./EasyDutch.all.txt
          popd > /dev/null
          cp $TMPDIR/EasyDutch/*.txt EasyDutch/
          cp $TMPDIR/EasyDutch.txt EasyDutch.txt
      - name: Patch last-updated field
        run: |
          DATE=$(date -Ru)
          for f in $(git diff --name-only); do
            STAT=$(git diff --numstat $f | sed -r '/^1\s+1\s+/d')
            if [[ -n $STAT ]]; then
              sed -ir "0,/^! Last updated: /s/^\(! Last updated: \)%timestamp%/\\1$DATE/" $f
            else
              git checkout -q $f
            fi
          done
      - name: Commit changes (if any)
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "GitHub-Actions"
            git config user.email "<>"
            git add -u EasyDutch/ EasyDutch.txt
            git commit -m "Update modified filter lists"
            git push origin gh-pages
          fi
