name: Delete old workflow runs 2
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3'

jobs:
  delete_runs:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          save_period: 0
          save_min_runs_number: 0
